apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: backstage-idp
  description: Internal Developer Platform using Backstage

  annotations:
    github.com/project-slug: rajudruva2/backstage-idp

spec:
  type: website
  lifecycle: experimental
  owner: user:default/rajudruva2
