apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: springboot-app
  title: Spring Boot Application
  description: Create a Spring Boot application repository
  tags:
    - java
    - springboot
    - kubernetes
  annotations:
    backstage.io/source-location: url:https://github.com/rajudruva2/backstage-idp/tree/main/templates/springboot-app
    backstage.io/managed-by-location: url:https://github.com/rajudruva2/backstage-idp/tree/main/templates/springboot-app

spec:
  owner: user:guest
  type: service

  parameters:
    - title: Application Information
      required:
        - appName

      properties:
        appName:
          title: Application Name
          type: string
          description: Name of the GitHub repository

  steps:
    - id: fetch
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/rajudruva2/backstage-idp/tree/main/templates/springboot-app/skeleton
        values:
          appName: ${{ parameters.appName }}

    - id: publish
      name: Publish Repository
      action: publish:github
      input:
        repoUrl: github.com?owner=rajudruva2&repo=${{ parameters.appName }}
        defaultBranch: main
        description: Spring Boot application created from Backstage

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
