name: Build, Push to ECR and Update GitOps Repo

on:
push:
branches:
- main

permissions:
id-token: write
contents: read

jobs:
build:
runs-on: ubuntu-latest

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 443407534093
  ECR_REPOSITORY: springboot

steps:
  - name: Checkout Source Code
    uses: actions/checkout@v4

  - name: Setup Java
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Build JAR
    run: mvn clean package

  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    with:
      role-to-assume: arn:aws:iam::443407534093:role/GitHubActionsECRPushRole
      aws-region: us-east-1

  - name: Login to Amazon ECR
    uses: aws-actions/amazon-ecr-login@v2

  - name: Set Variables
    run: |
      echo "IMAGE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
      echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

  - name: Build Docker Image
    run: |
      docker build \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_NAME}-${IMAGE_TAG} \
        -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_NAME}-latest .

  - name: Push Docker Image
    run: |
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_NAME}-${IMAGE_TAG}
      docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_NAME}-latest

  - name: Clone GitOps Repository
    run: |
      git clone https://x-access-token:${{ secrets.GITOPS_TOKEN }}@github.com/<ORG_NAME>/backstage-idp.git

  - name: Update Deployment Manifest
    run: |
      cd backstage-idp

      sed -i "s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_NAME}-${IMAGE_TAG}|g" environments/dev/deployment.yaml

  - name: Commit and Push Changes
    run: |
      cd backstage-idp

      git config user.name "github-actions"
      git config user.email "github-actions@github.com"

      git add .
      git commit -m "Update image tag to ${IMAGE_TAG}" || echo "No changes to commit"

      git push origin main

