# User Entity
apiVersion: backstage.io/v1alpha1
kind: User

metadata:
  name: rajudruva2

spec:
  profile:
    displayName: Raj Kumar
    email: rajudruva2@gmail.com

  memberOf:
    - admins

---
# Group Entity
apiVersion: backstage.io/v1alpha1
kind: Group

metadata:
  name: admins

spec:
  type: team

  profile:
    displayName: Platform Admin Team

  children: []
